jobs: 
  hello: 
    docker: 
      - 
        image: "circleci/node:12"
    steps: 
      - checkout
      - run: "echo \"hello world\""
        
  install: 
    docker: 
      - 
        image: "circleci/node:12"
    steps:
      - checkout
      - restore_cache:
         key: yarn-packages-{{ checksum "yarn.lock"}}
      - run : yarn global add node-gyp 
      - run : yarn install
      - save_cache:
         key: yarn-packages-{{ checksum "yarn.lock"}}
         paths:
          - ./node_modules
  lint: 
    docker: 
      - 
        image: "circleci/node:12"
    steps: 
      - checkout
      - restore_cache:
         key: yarn-packages-{{ checksum "yarn.lock"}}
      - run : yarn lint 
      - run : yarn format:check
      
  test: 
    docker: 
      - 
        image: "circleci/node:12"
    steps: 
      - checkout
      - restore_cache:
         key: yarn-packages-{{ checksum "yarn.lock"}}
      - run : yarn test:ci
  database: 
    docker: 
      - 
        image: "circleci/node:12"
        environnement:
          DATABASE_URL: postgres://psqluer:psqlpassword@localhost:5432/psdb
          JWT_SECRET: some string yo want
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
      -
        image: "circleci/postgres:9.6.2-alpine"
        environnement:
            POSTGRES_USER: psqluser
            POSTGRES_PASSWORD: psqlpassword
            POSTGRES_DB: psdb
    steps: 
      - checkout
      - restore_cache:
         key: yarn-packages-{{ checksum "yarn.lock"}}
      - run : yarn test:e2e
      
orbs: 
  node: circleci/node@3.0.0
version: 2.1
workflows: 
  tests: 
    jobs: 
      - hello
      - install
      - lint
      - test
      - database
